import ENResourcesIndex from '../../applications/constants/ENResourcesIndex';

module.exports = {
  ...ENResourcesIndex,
  breadcrumbHome: "Home",
  batchView_Heading: "Batch View",
  EntityWorkboard_Heading: "Organization Workboard",
  header_pending: "Pending",
  header_view_all: "view all",
  tile_RECON: "RECON",
  tile_progress: "progress",
  header_logout: "Log Out",
  Notifications_Heading: "Notifications",
  wgt_system: "System",
  takeAction: "Take action",
  Footer: "2017-18 © Avanza Solutions Private Ltd.",
  EWB_name: "Organization Name",
  EWB_lastSettlementDate: "Last Settlement Date",
  EWB_overDue: "Over Due",
  EWB_settlementPeriod: "Settlement Period",
  EWB_totalTransaction: "Total Transaction",
  EWB_pendingExceptions: "Pending Exceptions",
  EWB_refundFiled: "Refund Filed",
  EWB_lastDateRecon: "Last Date Recon",
  EWB_disputesFiled: "Disputes Filed",
  EWB_actions: "Action",
  AWB_name: "Acquirer Name",
  AWB_lastSettlementDate: "Last Settlement Date",
  AWB_overDue: "Over Due",
  AWB_settlementPeriod: "Settlement Period",
  AWB_totalTransaction: "Total Transaction",
  AWB_pendingExceptions: "Pending Exceptions",
  AWB_refundFiled: "Refund Filed",
  AWB_lastDateRecon: "Last Date Recon",
  AWB_disputesFiled: "Disputes Filed",
  AWB_actions: "Action",
  LastSettlementDate: "Transaction From Date",
  SettlementToDate: "Transaction To Date",
  PreviousResolvedExceptions: "Previous Resolved Exceptions",
  CurrentPeriodTrans: "Current Period Trans",
  ProcessedPastRefund: "Processed Past Refund",
  TotalPayable: "Total Payable",
  ToDate: "To Date",
  NetTotalAmount: "Net Total Amount",
  TotalCommissionAmount: "Total Commission Amount",
  TotalAmount: "Total Amount",
  Commission: "Commission",
  AppliedCommission: "Applied Commission",
  RefundCommission: "Refund Commission",
  TotalCommission: "Total Commission",
  ShowBreackupCommission: "show breakup commission",
  Download: "Download",
  BlockChainAddress: "Blockchain Address",
  DownloadFileMessage: "Please donwload the file",
  SettlementBatchExecutedMessage: "Settlement batch is executed view as",
  ViewCommissionBreakup: "View Commission Breakup",
  ViewSettlementDetail: "View Settlement Detail",
  CommissionBreakup: "Commission Breakup",
  Process: "Process",
  Reconcile: "Reconcile",
  AquirerWorkboard_Heading: "Aquirer Workboard",
  AWB_acquirer: "Acquirer",
  AWB_position: "Position",
  AWB_lastReconDate: "Last Recon Date",
  AWB_lastCommissionDisbusal: "Last Disbursal",
  AWB_commissions: "Commissions",
  AWB_refunded: "Refunded",
  SL_entityName: "Organization Name",
  SL_batchNo: "Batch No",
  SL_dateInitiated: "Date Initiated",
  SL_amount: "Amount",
  SL_commission: "Commission",
  SL_status: "Status",
  SL_action: "Action",
  SettlementList_Heading: "Settlement List",
  SB_PaymentMode: "Payment Mode",
  SB_CardType: "Card Type",
  SB_SettledAmount: "Settled Amount",
  SB_TotalNoTrans: "Total No. Trans",
  SB_InvoiceAmount: "Invoice Amount",
  SB_InvoiceCharges: "Invoice Charges",
  SB_RefundedAmount: "Refunded Amount",
  SB_RefundedTran: "Refunded Tran",
  SB_RefundedCharges: "Refunded Charges",
  SB_FinalInvoiceAmount: "Final Invoice Amount",
  COM_AB_Process: "Process",
  SB_Heading: "Pending Settlements",
  PS_Heading: "Processed Settlement",
  EL_entity: "Organization",
  EL_processor: "Acquirer",
  EL_date: "Date",
  EL_exceptionType: "Exception Type",
  EL_userID: "User ID",
  grd_exceptionList: "Exception List",
  EL_Header: "Exceptions",
  EL_actions: "Actions",
  EL_ePayRef: "ePay Ref No",
  TL_entity: "Organization",
  TL_SPTransNo: "SP Ref No",
  TL_DEGTransNo: "ePay Ref No",
  TL_PGTransNo: "PG Ref No",
  TL_ServiceProvider: "Organization",
  TL_Service: "Service",
  TL_TransactionDate: "Date",
  TL_Status: "Recon Status",
  FPS_Status: "File Status",
  TL_Amount: "Amount",
  TL_actions: "Actions",
  TL_Reason: "Errors",
  TL_Heading: "Transaction List",
  TL_Description: "Description",

  entityName: "Name",
  arabicName: "Arabic Name",
  isActive: "Is Active",
  isGRP: "GRP Enabled",
  isCTS: "CTS Enabled",
  parentEntity: "Parent Organization",
  AS_shortCode: "PG Code",
  ES_spCode: "Org Code",
  commissionTemplate: "commission Templates",
  exemptedTillDate: "Exempted Till Date",
  notifyBeforeMonth: "Notify Before(Month)",
  settlementType: "Settlement",
  SettlementCriteria: "Settlement Criteria",
  autoPeriod: "Auto Period Days",
  escalationAfter: "Escalation After Days",
  integrationType: "Recon Type",
  isBlockchain: "Blockchain",
  isFile: "File",
  isSFTP: "sFTP",
  isAutoReconService: "Auto Service",
  recon_label: "Recon Types:",
  Integrations_label: "Integrations:",
  fileFormatTemplate: "File Format Template",
  noOfDays: "Recon Period Days",
  username: "Username",
  password: "Password",
  EntitySetup_Heading: "Organization Setup",
  EntitySearchContainer_Heading: "Organization Search",
  ES_serviceName: "Service Name",
  ES_serviceCode: "Service Code",
  ES_contactName: "Contact Name",
  ES_email: "Email",
  ES_mobile: "Mobile",
  ES_sFTPServer: "sFTP Server",
  ES_port: "Port",
  ES_services_action: "Action",
  ES_contacts_action: "Action",
  ESEARCH_entityName: "Org Full Name",
  ESEARCH_arabicName: "Arabic Name",
  ESEARCH_status: "Status",
  ESEARCH_spCode: "Org Code",
  ESEARCH_orgType: "Org Type",
  ESEARCH_isActive: "Active",
  ESEARCH_action: "Action",

  /** 26-09-2017 */
  Refund_Heading: "Initiate Refund",
  IR_searchHeading: "Refund Information",
  IR_uploadHeading: "Comments & Upload",
  viewRefund_Heading: "View Refund",
  GEN_File: "File Name",
  GEN_Action: "Action",
  GEN_date: "Date",
  GEN_userID: "User ID",
  GEN_org: "Orginization",
  GEN_comments: "Comments",
  VR_searchHeading: "Refund Details",
  RL_searchHeading: "Refund Search",
  RL_refundList: "Refunded Transactions",
  RefundList_Heading: "Refund List",
  ID_uploadHeading: "Comments & Upload",

  btn_cancel: {
    "displayText": "Cancel",
    "displayClass": "btn primary"
  },
  btn_save: {
    "displayText": "Cancel",
    "displayClass": "btn primary"
  },


  /* new Test */

  MRS_type: "Type",
  MRS_count: "Count",
  MR_Process: "Process",
  MR_Reconile: "Reconcile",
  MRS_action: "Action",
  ManualRecon_Heading: "Manual Recon",

  MRA_date: "Date",
  MRA_reconAction: "Action",
  MRA_entityType: "Org Type",
  MRA_fileName: "File Name",
  MRA_userID: "User ID",
  MRA_ipAddress: "IP",
  MRA_status: "status",
  MRA_serviceCode: "Service Code",
  MRA_shortCode: "Code",
  MRA_action: "",

  CB_Heading: "Commission Disbursal",
  CB_summary: "Card Type",
  CB_amount: "Amount",
  CB_count: "Count",
  CB_LastCommissionDate: "Last Commission Date",
  CB_ToDate: "To Date",
  CB_CommissionSummary: "Commission Summary",
  CB_UploadFile: "Upload Files",
  CB_BAT_Process: "Process",

  CBP_Heading: "Commission Disbursal",
  CBP_Download: "Download",
  CBP_DownloadMessage: "Please download the file",
  CBP_BlockChainAddress: "Blockchain Address",
  CBP_CommissionBatchMessage: "Commission batch is executed view as",

  CL_Heading: "View Past Disbursed Commissions",
  CL_SearchHeading: "Past Disbursed Commission Filters",
  CL_GridHeading: "View Past Disbursed Commissions",
  CL_Processor: "Acquirer",
  CL_RefNo: "Batch No.",
  CL_StartDate: "From Date",
  CL_EndDate: "To Date",
  CL_Date: "Date",
  CL_AmountAED: "Amount(AED)",
  CL_status: "Status",
  CL_Commission: "Commissions",
  CL_actions: "Action",
  RL_refNo: "Refund Ref No",
  RL_date: "Date",
  RL_amount: "Amount",
  RL_acquirer: "Acquirer",
  RL_entity: "Organization",
  RL_status: "Status",
  RL_action: "Action",
  RL_ePayRefNo: "ePay Ref No",
  RL_SPRefNo: "SP Ref No",
  RL_PGRefNo: "PG Ref No",
  CD_Summary: "Description",
  CD_Amount: "Commission Amount",
  CD_TranAmount: "Transaction Amount",
  CD_Count: "Transactions Count",
  CL_BatchNo: "Batch No",


  CBV_SPRefNo: "SP Ref No",
  CBV_DGRefNo: "ePay Ref No",
  CBV_PFRefNo: "PG Ref No",
  CBV_TranData: "Tran Date",
  CBV_Amount: "Amount",
  CBV_Status: "Status",
  CBV_BlocchainID: "Blockchain No.",
  CBV_action: "",
  CBV_spCode: "Organization",
  CBV_pgCode: "Acquirer",
  CBV_Service: "Service",
  CBV_batchID: "Batch ID",

  // 10/10/17
  acquirerName: "Acquirer Name",
  acquirer_arabicName: "Arabic Name",
  ASEARCH_status: "Status",
  ASEARCH_shortCode: "PG Code",
  ASEARCH_isActive: "Active",
  ASEARCH_action: "Actions",
  AS_contactName: "Contact Name",
  AS_email: "Email",
  AS_mobile: "Mobile",
  AS_contacts_action: "Actions",
  AS_cardsType: "Cards Type",
  AS_cardName: "Card Name",
  AS_cardCode: "Card Code",
  AS_card_action: "Actions",
  AS_cardType: "Card Type",
  AS_fundsTransferSLAPeriod: "Funds Transfer SLA Period(Days)",
  AS_shadowAccount: "Shadow Account",

  FTEMP_fileName: "File Name(Regex)",
  FTEMP_fileType: "File Type",
  FTEMP_template_action: "Actions",
  FTEMP_templateName: "Template Name",
  FTEMP_separator: "Separator",
  FTEMP_skipLines: "Skip Lines",
  FTEMP_columnNo: "Column No",
  FTEMP_fieldNameTag: "Path To Tag",
  FTEMP_fieldName: "Field Name",
  FTEMP_internalField: "Internal Field",
  FTEMP_specialFunction: "Special Function",
  FTEMP_param1: "Param 1",
  FTEMP_param2: "Param 2",
  FTEMP_fields_action: "actions",
  FTEMP_required: "Required",
  FTEMP_fieldFormat: "Field Format(Regex)",
  FTEMP_maxLength: "Max Length",
  FTEMP_dataType: "Data Type",
  FTEMP_XMLMainTag: "Transactions Path",
  CTEMP_Preview: "Commission Template Preview",
  CTEMP_templateName: "Template Name",
  CTEMP_categoryType: "Category Type",
  CTEMP_feeType: "Fee Type",
  CTEMP_startDate: "Start Date",
  CTEMP_endDate: "End Date",
  CTEMP_minVal: "Tran Min(AED)",
  CTEMP_maxVal: "Tran Max(AED)",
  CTEMP_flatRate: "Flat",
  CTEMP_percentageRate: "Percentage",
  CTEMP_discount: "Discount",
  CTEMP_template_action: "Actions",

  ETEMP_templateName: "Template Name",
  ETEMP_subjectEng: "English Subject",
  ETEMP_subjectArabic: "Arabic Subject",
  ETEMP_templateType: "Type",
  ETEMP_templateTextEng: "Text Eng",
  ETEMP_templateTextArabic: "Text Arabic",
  ETEMP_placeHolder: "Available Place Holders",
  ETEMP_template_action: "Actions",


  RSEARCH_roleName: "Name",
  RSEARCH_roleDescription: "Description",
  RSEARCH_roleAction: "Action",
  USEARCH_userID: "User ID",
  USEARCH_firstName: "First Name",
  USEARCH_lastName: "Last Name",
  USEARCH_isActive: "Status",
  USEARCH_userAction: "Action",
  USEARCH_org: "Orginization",
  RList_roleName: "Name",
  RList_description: "Description",
  RList_roleID: "Role ID",
  WCD_exception: "Exception",
  WCD_start: "Start",
  WCD_end: "End",

  FU_fileName: "File Name",
  FU_dropMessage: "Drop files here or click to upload",
  FU_removeFileMessage: "Remove File",

  Tabel_noRecordFoundMessage: "No record found",

  TL_tranDetailHeading: "Transaction Detail",
  TL_tranPageHeading: "Transaction",

  EL_Heading: "Exception List",
  RA_Heading: "Recon Audit Trail",
  ES_Heading: "Organization Setup",
  ESearch_Heading: "Organization Search",
  BlockSearch_Heading: "Block Search",
  HashSearch_Heading: "Transaction Search",
  ConsortiumSearch_Heading: "Consortium Management",
  ConsortiumSetup_Heading: "Consortium",
  SmartContract_Heading: "Smart Contract",

  AQSearch_Heading: "Acquirer Search",
  AQSetup_Heading: "Acquirer Setup",
  ETSetup_Heading: "Email Template Setup",
  CSearch_Heading: "Commission Search",
  CSetup_Heading: "Commission Setup",
  FTSearch_Heading: "File Template Search",
  FTSetup_Heading: "File Template Setup",
  GSearch_Heading: "Group Search",
  GSetup_Heading: "Group Setup",
  USearch_Heading: "User Search",
  USetup_Heading: "User Setup",

  TLP_SearchFilter: "Transaction Search Filter",
  TLP_DetailHeading: "Transaction Detail",
  TLP_GridTitle: "Transactions",
  TLP_Close: "Close",
  TLPF_Entity: "Organization",
  TLPF_Processor: "Acquirer",
  TLPF_TranStatus: "Settlement Status",
  TLPF_DEGRefNo: "ePay Ref No",
  TLPF_SPRefNo: "SP Ref No",
  TLPF_PGRefNo: "PG Ref No",
  TLPF_FromDate: "From Date",
  TLPF_ToDate: "To Date",
  TLPF_ExceptionType: "Exception Type",


  submit: "Submit",
  Loading: "Loading..",
  Search: "Search",
  Clear: "Clear",
  Close: "Close",

  TD_ReferenceNo: "Reference Number",
  TD_DEGRefNo: "ePay Ref No:",
  TD_SPRefNo: "Organization Ref No:",
  TD_RefundRefNo: "Refund Ref No:",
  TD_SettlementRefNo: "Settlement Ref No:",
  TD_InvoiceRefNo: "Invoice Ref No:",
  TD_StatusIndicator: "Status Indicator",
  TD_DEGCapNo: "DEG Cap No:",
  TD_PGStatus: "PG:",
  TD_SPReconStatus: "SP Recon:",
  TD_DEGStatus: "ePay Recon:",
  TD_PGReconStatus: "PG Recon:",
  TD_AcqReconStatus: "Acquirer Recon:",
  TD_ManuallyRecon: "Manual Recon:",
  TD_ConfirmSerDel: "Confirm Service Delivery:",
  TD_OtherDetail: "Other Detail",
  TD_Entity: "Organization:",
  TD_PaymentGateway: "Payment Gateway:",
  TD_Service: "Organization Service:",
  TD_PaymentChannel: "Payment Channel:",
  TD_TransactionReqDate: "Trans Req Date:",
  TD_PaymentMethod: "Payment Method:",
  TD_TranCapDate: "Tran Capture Date:",
  TD_CardType: "Card Type:",
  TD_RefColl: "Refund Cancl Rmks:",
  TD_Amount: "Tran Amount:",
  TD_ePay: "ePay:",
  TD_CustomerEmail: "Customer Email:",
  TD_CustomerMobile: "Customer Mobile:",
  TD_IPAddress: "IP Address:",
  TD_AcquirerId: "Acquirer ID",
  TD_EntityName: "Organization Name:",
  TD_TranDate: "Transaction Date:",
  TD_TranStatus: "Transaction Status:",

  TD_RefundDate: "Refund Date:",
  TD_RefundStatus: "Refund Status:",
  TD_RefundID: "Refund ID:",
  TD_RefundRemarks: "Remarks:",

  TD_DisputeDate: "Dispute Date:",
  TD_DisputeStatus: "Dispute Status:",
  TD_DisputeID: "Dispute ID:",
  TD_DisputeRemarks: "Remarks:",

  TD_SettlementDate: "Settlement Date:",
  TD_SettlementID: "Settlement ID:",
  TD_SettlementStatus: "Settlement Status:",
  TD_SettlementRemarks: "Remarks:",


  TD_CommissionDate: "Commission Date:",
  TD_CommissionID: "Commission ID:",
  TD_CommissionStatus: "Commission Status:",
  TD_CommissionRemarks: "Remarks:",

  TD_PaymentStatus: "Payment Status:",
  TD_CaptureStatus: "Capture Status:",
  TD_ReconStatus: "Recon Status:",
  TD_ReconReason: "Reason:",

  TD_Acquirer: "Acquirer",

  EL_TransactionDetail: "Transaction Detail",
  ES_ExceptionsSearchFilter: "Exceptions Search Filter",
  MR_LastReconDate: "Last Recon Date",

  //30/10/17
  legacyCode: "legacy Code",
  MR_Service: "Service",
  STB_SearchSettlement: "Search Settlement",

  RA_ActionTypeDOF: "File Upload by DoF",
  RA_ActionTypeAcquirer: "File Upload by Acquirer",
  RA_ActionTypeEntity: "File Upload by Organization",
  RA_ActionTypeScreen: "Manual correction using Screen",
  RA_ActionTypeFTP: "File Upload via FTP",
  RA_ActionTypeAuto: "Auto Service Execution",
  RA_Filter: "Recon Audit Trail Filter",
  RA_FromDate: "From Date",
  RA_ToDate: "To Date",
  RA_Entity: "Organization",
  RA_Acquirer: "Acquirer",
  RA_ActionType: "Action Type",
  RA_Type: "Type",
  RA_Select: "Select",


  RAD_Heading: "Buyer Dashboard",
  RAD_ValSummary: "Validation Summary",


  RSEARCH_roleType: "Group Type",

  AL_event: "Event",
  AL_collectionName: "Collection",
  AL_ipAddress: "IP Address",
  AL_actionBy: "Action By",
  AL_actionOn: "Action On",
  AL_action: "Actions",

  Cipher_NodeSearch_Heading: "Node Search",
  Cipher_NodeSetup_Heading: "Node Setup",
  Cipher_Node: "Node Search",
  Cipher_NodeName: "Name",
  Cipher_NodeIP: "IP",
  Cipher_NodeDNSName: "DNSName",
  Cipher_NodePort: "Port",
  Cipher_NodeType: "Type",
  Cipher_NodeIsStatus: "Status",
  Cipher_NodeIsOrderer: "Orderer",
  Cipher_NodeIsEndorser: "Endorser",
  Cipher_NodeIsCommitter: "Committer",
  Cipher_SmartContractSearch_Heading: "Smart Contact Search",
  Cipher_SmartContractName: "Name",
  Cipher_SmartContractEventName: "Event Name",
  Cipher_SmartContractBindingId: "Binding Id",
  Cipher_SmartContractFileName: "Files",
  Cipher_SmartContractStatus: "Status",
  Cipher_SmartContractDesc: "Description",
  Cipher_SmartContractLanguage: "Language",
  Cipher_deployedChannels: "Channels",
  Cipher_deployedBy: "Deployed By",
  Cipher_deployedOn: "Deployed On",
  Cipher_deployedStatus: "Status",
  Cipher_BusinessAppName: "Name",
  Cipher_BusinessAppUsedBy: "Used By",
  Cipher_BusinessAppLoinURL: "Login URL",
  Cipher_ConsortiumOwnerType: "Type",
  Cipher_ConsortiumOwnerCode: "Code",
  Cipher_participantsType: "Type",
  Cipher_participantsCode: "Code",
  Cipher_participantsStatus: "Status",
  Cipher_participantsAccount: "Account",
  Cipher_action: "Action",

  TransactionDetail_Heading: "Transaction Detail",
  MarkReconciled: "Mark Reconcile",
  InitiateRefund: "Initiate Refund",
  InitiateDipute: "Initiate Dispute",
  MarkAuthorize: "Mark Authorize",

  RBL_BatchNo: "Batch No",
  RBL_date: "Date",
  RBL_acquirer: "Acquirer",
  RBL_entity: "Organization",
  RBL_status: "Status",
  RBL_action: "Action",

  TD_ServiceInfo: "Service Beneficiary Info",
  TD_serviceNameEn: "Service Name:",
  TD_serviceNameAR: "Service Name AR:",
  TD_serviceId: "Service ID:",
  TD_gessServiceId: "Gess Service ID:",
  SBD_accountID: "Account ID",
  SBD_txnAmount: "Txn Amount",
  SBD_fullName: "Full Name",
  SBD_email: "Email",
  SBD_emiratesID: "Emirates ID",
  SBD_type: "Type",
  SBD_company: "Company",
  SBD_tradeLicenseNo: "Trade License No",
  SBD_licenseIssuingAuth: "License Issuing",

  header_changePassword: "Change Password",
  ChangePassword_Heading: "Change Password",
  minimumPasswordLength: "Minimum Password Length",
  maximumPasswordLength: "Maximum Password Length",
  minimumAlphabetCount: "Minimum Alphabet Count",
  maximumAlphabetCount: "Maximum Alphabet Count",
  minimumDigitCount: "Minimum Digit Count",
  maximumDigitCount: "Maximum Digit Count",
  allowIncorrectLoginAttempts: "Allow Incorrect Login Attempts",
  minimumUpperCase: "Minimum Upper Case",
  minimumLowerCase: "Minimum Lower Case",
  lockTimeInMinutes: "Lock Time In Minutes",
  unAcceptedKeywords: "Unaccepted Keywords",
  changePeriodDays: "Change Period Days",
  errorMessage: "Error Message",
  PasswordPolicyHeading: "Password Policy",

  ChangePassword_CurrentPassword: "Current Password",
  ChangePassword_NewPassword: "New Password",
  ChangePassword_ConfirmNewPassword: "Confirm Password",
  ChangePassword_ChangePassword: "Change Password",

  TLPF_Acquirer: "Acquirer",
  TD_MaskedCardNo: "Masked Card No:",
  TD_ApprovalCode: "Approval Code:",

  EntityDetailReport_Heading: "Organization Detail Report",
  AcquirerDetailReport_Heading: "Acquirer Detail Report",

  RPT_Entity: "Organization",
  RPT_FromDate: "From Date",
  RPT_ToDate: "To Date",
  RPT_CardType: "Card Type",
  RPT_PaymentMethod: "Payment Method",
  RPT_TransactionStatus: "Recon Status",
  RPT_ReportFormat: "Report Format",
  RPT_PaymentGateway: "Payment Gateway",
  RPT_Acquirer: "Acquirer",
  RPT_Language: "Language",


  APL_FromDate: "From Date",
  APL_ToDate: "To Date",
  APL_UUID: "Message ID",
  APL_Channel: "Channel",
  APL_Action: "Action",
  APL_Date: "Date",
  APL_Actions: "",
  APL_PayloadField: "Payload Field",
  APL_PayloadFieldValue: "Payload Field Value",

  COM_SerialNo: "S.No",

  BlockChain_Heading: "Blockchain Viewer",
  BlockChainEditor_collectionNames: "Collection Name",
  BlockChainEditor_key: "Key",


  QR_transactionDetails: "Transaction Details",
  cipherSearchByHash: "Search By Hash",


  RV_fileName: "File Name",
  RV_status: "Status",
  RV_uploadedOn: "Uploaded on",
  RV_uploadedBy: "Uploaded By",

  RV_Comments: "Comments",
  RV_User: "User",
  RV_Reason: "Reason",
  RV_Date: "Date",
  RV_Status: "Status",
  view_Settlement_Batch: "Settlement Batch",
  view_Settlement_Batch_Detail: "Settlement Batch Detail",
  view_Commission_Batch: "Commission Batch Detail",
  EntitySummaryReport_Heading: "Organization Transaction Summary Report",
  AcquirerTranSummaryReport_Heading: "Acquirer Transaction Summary",

  RefundListView_Heading: "Create Refund Batch",
  RefundBatchList_Heading: "Refund Batch List",
  RefundReport_Heading: "Refund Report",
  BankCommission_Heading: "Bank Commission Report",
  RefundAndDisputeStats_Heading: "Refund And Dispute Stats Report",
  EntitySettlementReport_Heading: "Organization Settlement Report",


  TD_MarkReconcile_Heading: "Mark Reconcile",
  TD_MarkAuthorize_Heading: "Mark Authorize",
  TD_PGRefNo: "PGRefNo",
  TD_SPTRN: "SPTRN",
  TD_amount: "Amount",
  TD_remarks: "Remarks",
  NOTI_Level: "Level",
  NOTI_Message: "Message",
  NOTI_isArchive: "Archived",
  NOTI_Actions: "Actions",

  EntityReconReport_Heading: "Organization Recon Report",
  BankReconReport_Heading: "Bank Recon Report",

  RPT_ReconStatus: "Recon Status",
  RPT_SettlementStatus: "Settlement Status",

  SLA_KPI: "SLA KPI",

  TLPF_AuthorizedStatus: 'Authorization Status',

  RPT_PaymentStatus: 'Payment Status',
  entityMonthWiseReport_Heading: "Organization Month Wise Report",
  TSF_MobileNo: "Mobile No",
  TSF_Email: "Email Address",

  ReconReport_Heading: "Reconciliation Report",

  TLPF_IsRefunded: 'Refund Status',
  TLPF_IsSettled: 'Settlement Status',

  TLPF_Service: "Service",

  RPT_Service: "Service",

  SLA_img: "User Name",
  SLA_belowSLA: "SLA Burst",
  SLA_MeetSLA: "Meet SLA",
  SLA_column: "SLA",
  SLA_Cnt: "Total Count",
  SLA_Actions: "Actions",
  SLAWorkboard_Heading: "SLA",

  TD_userId: "User ID:",
  TD_userName: "User Name:",
  TD_fullNameEn: "Full Name En:",
  TD_fullNameAr: "Full Name Ar:",
  TD_mobileNo: "Mobile No:",
  TD_email: "Email:",
  TD_nationalityCode: "Nationality Code:",
  TD_emiratesId: "Emirates ID:",
  TD_emirateCode: "Emirates Code:",
  TD_pobox: "PO Box:",


  LastCommissionDate: "Last Commission Date",


  ID_searchHeading: "Dispute Information",
  Dispute_Heading: "Initiate Dispute",
  DL_searchHeading: "Dispute Search",
  DL_refundList: "Disputed Transactions",
  DisputeListView_Heading: "Create Dispute Batch",
  viewDispute_Heading: "View Dispute",
  DisputeList_Heading: "Dispute List",
  DisputeBatchList_Heading: "Dispute Batch List",
  DL_disputeList: "Disputed Transactions",
  DBL_Entity: "Organization",
  KPIEntityWorkBoard_Heading: "KPI Workboard",

  CostAnalysisReport_Heading: "Cost Analysis Report",

  DisputeReport_Heading: "Dispute Report",
  ViewDisputeBatch_Heading: "Dispute Batch Detail",
  DSPT_searchHeading: "Dispute Search",
  DL_refNo: "Dispute Ref No",
  header_lock: "Lock",
  ViewCommissionDetail: "View Commission Detail",
  ViewRefundBatch_Heading: "View Refund Detail",

  DBL_List: "Dispute Batches",
  DBL_searchHeading: "Batch Search Filters",
  RBL_refundList: "Refund Batches",
  RBL_searchHeading: "Batch Search Filters",

  TSF_PaymentStatus: "Payment Status",
  SL_netTotalAmount: "Net Total Amount",
  TL_PaymentStatus: "Payment Status",
  EL_PaymentStatus: "Payment Status",
  ViewRefundBatchDetail_Heading: "Refund Batch Detail",
  TLPF_validationSummary: "Validation Summary",

  USEARCH_userType: "User Type",

  CBV_Commission: "Commission",
  TD_SettlementAmount: "DOF Commission:",
  TD_CommissionAmount: "Bank Charges:",

  RBL_TotalTran: "Total Tran",
  blockchainWorkboard_Heading: "Block Explorer",
  BWB_Number: "Block Number",
  BWB_FROM: "From",
  BWB_TO: "To",
  BWB_VALUE: "Value",
  BWB_Size: "Block Size",
  BWB_Hash: "Block Hash",
  BWB_Nonce: "Nonce",
  BWB_Timestamp: "Creation Time",
  BWB_Action: "Action",
  BTL_blockNumber: "Block Number",
  BTL_transactionIndex: "index",
  BTL_to: "to",
  BTL_from: "from",
  BTL_gas: "gas",
  BTL_gasPrice: "gasPrice",
  BTL_hash: "Hash",
  BTL_input: "Input",
  BTL_nonce: "Nonce",
  BTL_value: "Value",
  BTL_Hex: "Input Hex",
  BTL_InputUTF8: "Input UTF8",
  BTL_logData: "Log Data",
  BTL_Heading: "Block Transaction List",
  BLTLP_SearchFilter: "Block Transaction Search Filter",
  BLTLP_DetailHeading: "Block Transaction Detail",
  BLTLP_GridTitle: "Block Transactions",


  Cipher_consortiumName: "Consortium Name",
  Cipher_consortiumType: "Blockchain Type",
  Cipher_consortiumAction: "Action",
  Cipher_channelName: "Channel Name",
  Cipher_channelOrgs: "Organizations",
  Cipher_channelAction: "Action",
  cipher_orgName: "Organization Name",
  cipher_nodeName: "Node Name",

  PL_TypeName: "Type Name",
  PLIST_Name: "Pick List Name",
  PLIST_Key: "Label",
  PLIST_Value: "Value",
  PickupList_Heading: "Pickup List",
  PickupListSetup_Heading: "Pickup List Setup",

  HML_servicesName: "Service",
  HML_containerID: "Container ID",
  HML_dockerIP: "Docker IP",
  HML_status: "Status",
  HML_lastTime: "Last Update",
  HML_errorDesc: "Error Description",
  HML_Heading: "Services Health Monitor",

  RBL_TotalAmount: "Total Amount",

  TSF_BasicSearch: "Basic Search",
  TSF_AdvanceSearch: "Advance Search",
  TSF_ApprovalCode: "Approval Code",
  TSF_MaskedCard: "Masked Card",
  TSF_PaymentMethod: "Payment Method",
  TSF_CardType: "Card Type",

  TDA_Status: "Status",
  TDA_Date: "Action Date",
  TDA_CreatedBy: "Action By",
  TDA_Remarks: "Remarks",

  TD_RefundCreatedBy: "Created By:",
  RPT_PaymentChannel: "Payment Channel",

  Audit_Log: "Audit Log",
  TLPF_ReconStatus: "Recon Status",


  SampleCrudPage_Heading: "Sample Crud Page",
  SampleCrudPage_Textbox: "Textbox",
  SampleCrudPage_Dropdown: "Dropdown",
  SampleCrudPage_Date: "Date",
  SampleCrud_Popup: "Popup Section",
  SampleCrud_InputGrid: "Input Grid Section",

  SampleCrud_Grid_Code: "Code",
  SampleCrud_Grid_Description: "Description",
  SampleCrud_Grid_Quantity: "Quantity",
  SampleCrud_Grid_Value: "Value",
  SampleCrud_Grid_Action: "Action",
  SampleCrud_Grid_Container: "Container",
  SampleCrud_AttachementSection: "Attachment Section",

  Buyer_Heading: "Buyer Dashboard",
  Merchant_Heading: "Merchant Dashboard",
  RewardsProvider_Heading: "Rewards Provider Dashboard",

  policyType: "Policy Type",
  InitiatePending: "Initiating",
  CancelPending: "Cancelling",
  EventListFilters: "Event List Filters",
  EventList: "Registered Event List",
  DatasourceListFilters: "Datasource List Filters",
  DatasourceList: "Datasource List",
  EL_DataSource: "Data Source",
  EL_Dispatcher: "Dispatcher",
  EVNTL_EVENTNAME: "Event Name",
  EVNTL_DATASOURCE: "Event DataSource",
  EVNTL_DIPATCHER: "Event Dispatcher",
  EVNTL_ISACTIVE: "Active",
  EVNTL_CREATEDBY: "Created By",

  DL_DataSource: "Data Source Name",
  DL_Function: "Function",
  DL_FilePath: "File Path",

  AddUpdateDatasource: "Add / Update Datasource",

  AddUpdateDataEventsRules: "Event Rules Details",
  AddUpdateDatasourceRules: "Datasource Defination",
  AddUpdateDatasourceFilters: "Add / Update Datasource Fiters",
  AddUpdateEventListFilters: "Event Details",
  EAU_EventName: "Event Name",
  EAU_Datasource: "Data Source",
  EAU_Dispatcher: "Dispatcher",
  EAU_EventTemplate: "Event Template",
  EAU_TemplateFields: "Field",
  EAU_Operator: "Operator",
  EAU_Value: "Value",
  AddUpdateEventList: "Add / Update Event",
  EAU_isActive: "is Active",
  DSR_TemplateFields: "Field",
  DSR_Type: "Type",
  EVNTL_ID: "Request ID",
  EVNTL_Date: "Event Date",
  EVNTL_DispatchDate: "Dispatch Date",
  EL_Error: "Error",
  EL_Status: "Status",
  BWB_Time: "Block Timestamp",
  BWB_Type: "Tranx Type",
  BWB_TimeStamp: "Blockchain Time",
  BTL_channelID: "Channel",
  BTL_Version: "Version",
  BTL_MSP: "Provider",
  BTL_TCERT: "Transaction Certificate",
  BTL_Payload: "Chaincode PayLoad",
  BTL_logs: "Logs",
  NoRecordsFound: "No Records Found!",
  MAU_Field: "Field Name",
  MAU_Value: "Value",
  MAU_Type: "Field Type",
  MAU_Datatype: "Data Type",
  MAU_Function: "Function Name",
  MAU_Validation: "Validation",
  MAU_Description: "Description",
  MappedField: "Mapped Field",
  IncommingField: "Incomming Field",
  AddUpdateMapping: "Add/Update Mapping Configuration",
  MAU_RequestName: "Mapping Name",
  MAU_RequestType: "Mapping Type",
  MAU_RequestDescription: "Description",
  customMappingDefination: "Configuration Definition",
  MAU_incField: "Incomming Field",
  MAU_incDataType: "Incomming Field DataType",
  MAU_mapField: "Mapped Field",
  MAU_mapDataType: "Mapped Field Data Type",
  MAU_incFieldType: "Incomming Field Type",
  MAU_Seq: "Field Sequence",
  MAU_Required: "Required",
  MAU_IN_ISREQUIRED: "Required",
  APIDefinitionScreen_Heading: "API Configuration ",
  APIDefScreen_route: "Route",
  APIDefScreen_isActive: "Active",
  APIDefScreen_Authorization: "Authorization",
  APIDefScreen_Label1: "Dynamic Route Calling",
  APIDefScreen_RouteOveride: "RouteOverride",
  APIDefScreen_fieldName: "FieldName",
  APIDefScreen_Label2: "Custom Function File",
  APIDefScreen_CustomMapping: "Custom Mapping",
  APIDefScreen_MFunctionName: "Mapping Function Name",
  APIDefScreen_CFileName: "Custom File Name",
  APIDefScreen_Label3: "Message Type",
  APIDefScreen_async: "Asynchronous",

  APIDefScreen_Dropdown2: "dropDown2",
  APIDefScreen_RSQueue: "Request Service Queue",
  APIDefScreen_ServiceURL: "Service URL",
  APIDefScreen_ResponseQueue: "Response Queue",
  APIDefScreen_isSimulated: "isSimulated",
  APIDefScreen_ServiceHeader: "HTTP Headers",
  APIDefScreen_Label4: "API Description",
  APIDefScreen_Label5: "Simulator Response",
  APIDefScreen_RequestMapping: "Request Mapping",
  APIDefScreen_ResponseMapping: "Response Mapping",
  ApiList: "System API List",
  ApiListDataFilters: "API List Filters",
  AAU_UseCase: "Use Case",
  AAU_Route: "Route",
  AAU_isSimulated: "Simulator",
  AAU_isActive: "Active",
  DOC_FIELD: "Field Name",
  DOC_DESCRIPTION: "Description",
  DOC_Type: "Field Type",
  DOC_REQUIRED: "Required",
  AAU_Doc: "Documentation Link",
  MAU_useCase:"Use Case",
  MAU_TypeData:"Enum",
  APIDefScreen_Label6:"Rule Based Simulator",
  APIDefScreen_SimuField:"Request Field",
  APIDefScreen_SimuValue:"Equals Value",
  APIDefScreen_RuleName:"Rule Name",
  MappingListDataFilters:"Mapping Configurations",
  MappingList:"Mapping Config List",
  MDAU_iconName:"Icon Name",
  MDAU_label:"Module Label",
  MDAU_order:"Menu Order",
  MDAU_displayMenu:"Display Menu",
  MDAU_ParentValue:"Parent ID",
  MDAU_PageValue:"Permission ID",
  MDAU_actionType:"Action Type",
  MDAU_value:"Permission ID",
  MDAU_Type:"Permission Type",
  MDAU_PageLabel:"Permission Label",
  MDAU_PageURI:"UI URI",
  MDAU_labelName:"Label Ref Name",
  MDAU_APIName:"Listed APIs",
  MDAU_CustomApi:"Non Listed API/URI",
  MDAU_APIDefinition:"Permissioned APIs",
  ModuleDefinitionScreen_Heading:"System Module Update",
  ModuleDefinationForm_Heading:"Module Details",
  PermissionList:"Permission List",
  MDAU_PageDefinition:"Permission Add/Update",
  MDAU_ParentName:"Parent Label",
  MAU_ApiUri:"Permissioned API / URI",
  ModuleListDataFilters:"System Module List",
  ModuleList:"Module Search",
  AAU_label:"Module Label",
  dispatchContainer_Heading:"Event Dispatcher Configuration",
  DC_DispatcherDefiniation:"Dispatcher Configuration",
  DC_dispatcherName:"Dispatcher Name",
  DC_type:"Dispatch Type",
  DC_filePath:"Custom File Path",
  DC_dispatchFunction:"Custom Function Name",
  DC_groupName:"Email Group Name",
  DC_emailTemplate:"Email Template",
  DC_requestURL:"Request URI",
  DC_requestHeader:"Request Header",
  DC_requestBody:"Request Body",
  DL_SourceType:"Data Source Type",
  DL_QueueName:"Queue Name",
  NetworkConfiguration:"Network Configuration",
  CAURL:"CA URL",
  CASecret:"Secret",
  CAUserName:"Username",
  CertificateAuth:"Certificate Authority Configuration",
  ordererDefinition:"Ordering Service Configuration",
  OrdererURL:"Service URL",
  ServerName:"Server Name (DNS)",
  cacertificate:"TLS Certificate",
  orgDefinition:"Channel Organization Configuration",
  MSPID:"Membership Service Provider",
  channel:"Channel Name",
  peerDefinition:"Peer(s) Service Configuration",
  peerName:"Peer Name",
  requestURL:"Request URL",
  eventURL:"Event URL",
  UserDefination:"Orginization Users Definition",
  NetworkDefinitionScreen_Heading:"Network Configuration",
  orginizationAlias:"Network Alias",
  NAU_networkName:"Network Name",
  NAU_MSPID:"MSP ID",
  NAU_orginizationAlias:"Org Alias",
  NAU_createdBy:"Created By",
  NetworkListDataFilters:"Search Filters",
  NetworkList:"Network List",
  Channel:"Create Channel",
  Channel_Name : "Channel Name",
  Create_Channel:"Create Channel",
  Network:"Network",
  Create_Status:"Channel Creation Response Status",
  Joinchannel:"Join Channel",
  Join_Status:"Join Status",
  PeerList:"Peer List",
  Playground:"Playground",
  SmartContract_Name:"SmartContract Name",
  Function_Name:"Function Name",
  RequestType:"Request Type",
  Parameters:"Parameters",
  Response:"Response",
  Network_Peers:"Network Peers",
  NAU_channelName:"Channel Name",
  ChannelListDataFilters:"Channel Search",
  ChannelList:" Channels",
  smartContract_Name:"Smart Contract Name",
  smartContract_Version:"Smart Contract Version",
  endorsementPolicy: "Endorsement Policy",
  smartContractArgs:"Initialization Arguments",
  smartContractMethod:"Initialization Function",
  SmartContract:"SmartContract Configuration",
  SmartContractCreate_Status:"Response From Blockchain",
  CreateSmartContract_Heading:"SmartContract",
  NAU_smartContract:"Smart Contract Name",
  SmartContractListDataFilters:"Smart Contract Search",
  SmartContractList:"Smart Contracts",
  smartContractInput:"Smart Contract Input",
  smartContractMethodInput:"Smart Contract Method",
  smartContractArgsInput:"Method Arguments",
  SmartContractInput:"Contract",
  SmartContractPlayGround:"Blockchain PlayGround",
  dispatcherDefination:"Dispather Setting",
  particapantDefinition:"Particapant Defination",
  OrganizationName:"Organization",
  ParticapantType:"Particapant Type",
  ParticipantName:"Participant Name",
  CM_useCase:"Buisness Applications",
  Consortium_Name:"Consortium Name",
  CreateConsortium:"Blockchain Consortium",
  APIDefScreen_FieldValue:"Org ID Value Equals ",
  APIDefScreen_OrgField:"Org ID Field ",
  blockchainRouting:"Routing Configuration",
  APIDefScreen_isBlchn:"Blockchain Request",
  useCase:"Application",
  APIMetering:"API Metering",
  EnableBilling:"Enable Billing",
  BillingDate:"Start Date",
  Generate_ChainCode :"Generate ChainCode",
  TargetField:"Target Field",
  TransformationSettings:"Transformation Settings",
  TRAN_Field:"Field Name",
  Transformation_Type:"Action Type",
  TRAN_TypeData:"Type Data",
  TRAN_Function:"Transformation Function",
  MessageCustomizations:"Message Customizations",
  DC_requestURI:"Request URI",
  DC_requestTemplate:"Request Template",
  EndPointName:"EndPointName",
  EVNTL_RetryCount:"Retry",
  APIDefScreen_ServiceURI:"Service URI",
  APIDefScreen_ServiceEndPoint:"Service End Point",
  GetStruct : "GetStruct",
  MAU_route:"API Route",
  MAU_ExistingMapping:"Existing Mapping",
  ApiImport:"API Import",
  AddUpdateAPIImp:"Add / Update API import",
  ConstellationId:"Constellation ID",
  MAU_ComplexTypeData:"Complex Types"
};
